In [3]:
# Importing Libraries
import pandas as pd
import numpy as np

# Extend sample dataframe
data = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace', 'Hannah', 'Ian', 'Jack'],
    'Age': np.random.randint(20, 40, size= 10),
    'Score': np.random.randint(35, 100, size= 10),
    'Country': np.random.choice(['USA', 'Canada', 'UK', 'Germany', 'France'], size=10),
    'Salary': np.random.randint(40000, 120000, size=10)
})

print("Original DataFrame:")
print(data)

Original DataFrame:
      Name  Age  Score  Country  Salary
0    Alice   23     72   France   50869
1      Bob   32     80  Germany   92563
2  Charlie   33     78  Germany   99539
3    David   26     74      USA  117170
4      Eva   21     64  Germany   55974
5    Frank   30     52  Germany   91929
6    Grace   23     74   Canada  100510
7   Hannah   35     82   Canada   75829
8      Ian   33     69      USA   91164
9     Jack   35     66  Germany   58724

In [6]:
# Sorting data by Country
sorted_data = data.sort_values(by=['Country', 'Score'], ascending=[True, False]) 
print("\nSorted DataFrame by Country and Score (Score in descending order and Country in Ascending Order): ")
display(sorted_data)

Sorted DataFrame by Country and Score (Score in descending order and Country in Ascending Order):

      Name  Age  Score  Country  Salary
7   Hannah   35     82   Canada   75829
6    Grace   23     74   Canada  100510
0    Alice   23     72   France   50869
1      Bob   32     80  Germany   92563
2  Charlie   33     78  Germany   99539
9     Jack   35     66  Germany   58724
4      Eva   21     64  Germany   55974
5    Frank   30     52  Germany   91929
3    David   26     74      USA  117170
8      Ian   33     69      USA   91164

In [7]:
# Sorting data by Age
sorted_data = data.sort_values(by=['Age', 'Salary'], ascending=[True, False])
print("\nSorted DataFrame by Age (Age in Ascending Order and Salary in Descending Order): ")
display(sorted_data)

Sorted DataFrame by Age (Age in Ascending Order and Salary in Descending Order):

      Name  Age  Score  Country  Salary
4      Eva   21     64  Germany   55974
6    Grace   23     74   Canada  100510
0    Alice   23     72   France   50869
3    David   26     74      USA  117170
5    Frank   30     52  Germany   91929
1      Bob   32     80  Germany   92563
2  Charlie   33     78  Germany   99539
8      Ian   33     69      USA   91164
7   Hannah   35     82   Canada   75829
9     Jack   35     66  Germany   58724