In [18]:
import pandas as pd
import numpy as np

# Creating Sample Datasets
a = pd.DataFrame({
    'A': [1, 2, 6, 4, 5],
    'B': [np.nan, 2, 3, 4, 5],
    'C': [np.nan, 2, 3, 4, np.nan]
})

# Displaying the original DataFrame
print("DataFrame:\n", a)

# Dropping rows with any NaN values
df_dropna_rows = a.dropna()
print("\nDataFrame after dropping rows with any NaN values:")
display(df_dropna_rows)

# Dropping columns with any NaN values
df_dropna_columns = a.dropna(axis=1)
print("\nDataFrame after dropping columns with any NaN values:")
display(df_dropna_columns)

DataFrame:
    A    B    C
0  1  NaN  NaN
1  2  2.0  2.0
2  6  3.0  3.0
3  4  4.0  4.0
4  5  5.0  NaN

DataFrame after dropping rows with any NaN values:

   A    B    C
1  2  2.0  2.0
2  6  3.0  3.0
3  4  4.0  4.0

DataFrame after dropping columns with any NaN values:

   A
0  1
1  2
2  6
3  4
4  5

DataFrame after dropping rows with any NaN values:

     A    B    C
1  2.0  2.0  2.0
3  4.0  4.0  4.0

In [19]:
df_dropna_specific = a.dropna(subset=['B', 'C'])
print("\nDataFrame after dropping rows with NaN values in specific columns (B and C):")
display(df_dropna_specific)

DataFrame after dropping rows with NaN values in specific columns (B and C):

   A    B    C
1  2  2.0  2.0
2  6  3.0  3.0
3  4  4.0  4.0

In [ ]:
# Dropping rows with NaN values in specific columns (B)
df_dropna_specific = a.dropna(subset=['B'])
print("\nDataFrame after dropping rows with NaN values in specific columns (B):")
display(df_dropna_specific)

DataFrame after dropping rows with NaN values in specific columns (B):

   A    B    C
1  2  2.0  2.0
2  6  3.0  3.0
3  4  4.0  4.0
4  5  5.0  NaN