# *Merge*

In [1]:
import pandas as pd

df_id = pd.DataFrame({
    'ID': [1, 2, 3, 4, 5],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva']
})

df_orders = pd.DataFrame({
    'ID': [1, 2, 3, 4, 5],
    'Amount': [250, 150, 200, 300, 400],
    'Order ID' : [101, 102, 103, 104, 105]
})

# Merging the DataFrames on 'ID'
df_merged = pd.merge(df_id, df_orders, on='ID')
print("Merged DataFrame:")
display(df_merged)

Merged DataFrame:

   ID     Name  Amount  Order ID
0   1    Alice     250       101
1   2      Bob     150       102
2   3  Charlie     200       103
3   4    David     300       104
4   5      Eva     400       105

# *Concat*

In [ ]:
df_sale_mar = pd.DataFrame({
    "Date" : ['2024-03-01', '2024-03-02', '2024-03-03', '2024-03-04', '2024-03-05'],
    "Sale" : [150, 200, 250, 300, 350]
})

df_sale_apr = pd.DataFrame({
    "Date" : ['2024-04-01', '2024-04-02', '2024-04-03', '2024-04-04', '2024-04-05'],
    "Sale" : [180, 220, 270, 320, 370]
})

# Concatenating the DataFrames
df_sales = pd.concat([df_sale_mar, df_sale_apr], ignore_index=True)  # Resetting index
print("Concatenated DataFrame:")
display(df_sales)

Concatenated DataFrame:

         Date  Sale
0  2024-03-01   150
1  2024-03-02   200
2  2024-03-03   250
3  2024-03-04   300
4  2024-03-05   350
5  2024-04-01   180
6  2024-04-02   220
7  2024-04-03   270
8  2024-04-04   320
9  2024-04-05   370

## *pd.merge and pd.concatenate*

In [ ]:
import pandas as pd

df_sale_mar = pd.DataFrame({
    'Product':['Apple', 'Banana', 'Orange', 'Mango', 'Grapes'],
    "Date" : ['2024-03-01', '2024-03-02', '2024-03-03', '2024-03-04', '2024-03-05'],
    "Sale" : [150, 200, 250, 300, 350]
})

df_sale_apr = pd.DataFrame({
    "Product':['Apple', 'Banana', 'Orange', 'Mango', 'Grapes'],"
    "Date" : ['2024-04-01', '2024-04-02', '2024-04-03', '2024-04-04', '2024-04-05'],
    "Sale" : [180, 220, 270, 320, 370]
})

df_id = pd.DataFrame({
    'ID': [1, 2, 3, 4, 5],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva']
})

df_orders = pd.DataFrame({
    'ID': [1, 2, 3, 4, 5],
    'Amount': [250, 150, 200, 300, 400],
    'Order ID' : [101, 102, 103, 104, 105]
})

# Step 1
df_sale = pd.concat([df_sale_mar, df_sale_apr], ignore_index=True)  # Resetting index
print("Combined DataFrame:")
print(df_sale)

# Step 2
df_final = pd.merge(df_sale, df_orders, on='Product', how='left')
print("Final Merged DataFrame:")
print(df_final)

Combined DataFrame:
  Product        Date  Sale  \
0   Apple  2024-03-01   150
1  Banana  2024-03-02   200
2  Orange  2024-03-03   250
3   Mango  2024-03-04   300
4  Grapes  2024-03-05   350
5     NaN         NaN   180
6     NaN         NaN   220
7     NaN         NaN   270
8     NaN         NaN   320
9     NaN         NaN   370

  Product':['Apple', 'Banana', 'Orange', 'Mango', 'Grapes'],Date
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN
5                                         2024-04-01
6                                         2024-04-02
7                                         2024-04-03
8                                         2024-04-04
9                                         2024-04-05
Final Merged DataFrame:
  Product        Date  Sale Category  Price
0   Apple  2024-03-01   150    Fruit     50
1  Banana  2024-03-02   200    Fruit     20
2  Orange  2024-03-03   250    Fruit     30
3   Mango  2024-03-04   300    Fruit     40
4  Grapes  2024-03-05   350    Fruit     60