In [11]:
import pandas as pd

# Creating a Sample DataFrame
data = {
    'Date': ['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04', '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08', '2023-01-09'],
    'Product': ['X', 'X', 'Y', 'Y', 'Z', 'Z', 'X', 'Y', 'Z'],
    'Region': ['North', 'North', 'South', 'South', 'East', 'East', 'West', 'West', 'West'],
    'Units': [10, 20, 30, 40, 50, 60, 70, 80, 90],
    'Sales': ['Jack', 'Sim', 'Tim', 'Sim', 'Jack', 'Sim', 'Tim', 'Sim', 'Jack'],
    'Profit': [100, 200, 300, 400, 500, 600, 700, 800, 900]
}

df = pd.DataFrame(data)

print("Original dataframe: ",)
display(df)

# Creating a Pivot Table
# Total Units by Product and Region
pivot_table_units = pd.pivot_table(df, index='Product', columns='Region', values='Units', aggfunc='sum', fill_value=0)
print("Pivot Table (Units): Total Units by Product and Region")
display(pivot_table_units)

# Total Profit by Product and Sales
pivot_table_profit = pd.pivot_table(df, index='Product', columns='Sales', values='Profit', aggfunc='mean', fill_value=0)
print("Pivot Table (Profit): Average Profit per Sales for each Product")
display(pivot_table_profit)

# Total and Average Units by Product for each Region
pivot_table_double = pd.pivot_table(df, index='Product', columns='Region', values='Units', aggfunc=['sum', 'mean'], fill_value=0)
print("Pivot Table (Units): Total and Average Units by Product for each Region")
display(pivot_table_double)

Original dataframe:

         Date Product Region  Units Sales  Profit
0  2023-01-01       X  North     10  Jack     100
1  2023-01-02       X  North     20   Sim     200
2  2023-01-03       Y  South     30   Tim     300
3  2023-01-04       Y  South     40   Sim     400
4  2023-01-05       Z   East     50  Jack     500
5  2023-01-06       Z   East     60   Sim     600
6  2023-01-07       X   West     70   Tim     700
7  2023-01-08       Y   West     80   Sim     800
8  2023-01-09       Z   West     90  Jack     900

Pivot Table (Units): Total Units by Product and Region

Region   East  North  South  West
Product
X           0     30      0    70
Y           0      0     70    80
Z         110      0      0    90

Pivot Table (Profit): Average Profit per Sales for each Product

Sales     Jack    Sim    Tim
Product
X        100.0  200.0  700.0
Y          0.0  600.0  300.0
Z        700.0  600.0    0.0

Pivot Table (Units): Total and Average Units by Product for each Region

         sum                   mean
Region  East North South West  East North South  West
Product
X          0    30     0   70   0.0  15.0   0.0  70.0
Y          0     0    70   80   0.0   0.0  35.0  80.0
Z        110     0     0   90  55.0   0.0   0.0  90.0